### PR TITLE
PgQuery.parse: Support complex queries with deeply nested ASTs

### LINKED ISSUE #209: Failed to parse tree: Error occurred during parsing
After upgrading I am suddenly starting to get these errors? There isn't much to go from in the error message.

The query is pretty long and generated using CanCan and Ransack:
```
SELECT "contacts"."contact_type", "contacts"."created_at", "contacts"."deleted_at", "contacts"."id", "contacts"."name", "contacts"."organization_id", "contacts"."person_id", "contacts"."state", "contacts"."student_council_id", "contacts"."updated_at" FROM "contacts" LEFT OUTER JOIN "organizations" ON "organizations"."id" = "contacts"."organization_id" LEFT OUTER JOIN "people" ON "people"."id" = "contacts"."person_id" WHERE (EXISTS (SELECT 1 FROM "contacts" AS "aliased_table" WHERE "aliased_table"."id" = "contacts"."id" AND EXISTS (SELECT 1 FROM "contacts" LEFT OUTER JOIN "contact_relationships" ON "contact_relationships"."relationship_type" = 'relative' AND "contact_relationships"."child_id" = "contacts"."id" LEFT OUTER JOIN "contacts" "parents_contact_relationships" ON "parents_contact_relationships"."id" = "contact_relationships"."parent_id" LEFT OUTER JOIN "photo_sessions" ON "photo_sessions"."customer_id" = "contacts"."id" LEFT OUTER JOIN "photo_session_groups" ON "photo_session_groups"."photo_session_id" = "photo_sessions"."id" LEFT OUTER JOIN "photo_session_group_contacts" ON "photo_session_group_contacts"."photo_session_group_id" = "photo_session_groups"."id" WHERE (("photo_sessions"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("photo_session_group_contacts"."contact_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "photo_session_group_contacts"."tenant_id" = '095b0a5d-c735-4f09-a906-49dfbe179594') OR (("photo_session_group_contacts"."contact_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "photo_session_group_contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("photo_session_group_contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("photo_session_groups"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR ((EXISTS (SELECT 1 FROM "election_post_contacts" WHERE (EXISTS (SELECT 1 FROM "election_post_contacts" AS "aliased_table" WHERE "aliased_table"."id" = "election_post_contacts"."id" AND EXISTS (SELECT 1 FROM "election_post_contacts" LEFT OUTER JOIN "election_posts" ON "election_posts"."id" = "election_post_contacts"."election_post_id" LEFT OUTER JOIN "elections" ON "elections"."id" = "election_posts"."election_id" LEFT OUTER JOIN "activities" ON "activities"."id" = "elections"."activity_id" LEFT OUTER JOIN "activity_participants" ON "activity_participants"."activity_id" = "activities"."id" WHERE (("election_post_contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("activity_participants"."contact_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "activity_participants"."state" IN ('approved', 'enrolled') AND "election_post_contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("election_post_contacts"."contact_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "election_post_contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("activity_participants"."contact_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "activity_participants"."state" IN ('approved', 'enrolled') AND "election_post_contacts"."tenant_id" = '095b0a5d-c735-4f09-a906-49dfbe179594') OR ("election_post_contacts"."contact_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "election_post_contacts"."tenant_id" = '095b0a5d-c735-4f09-a906-49dfbe179594'))))) AND ("election_post_contacts"."id" = "aliased_table"."id")))) AND (election_post_contacts.contact_id = contacts.id))) OR ((EXISTS (SELECT 1 FROM activities WHERE location_id = contacts.id)) OR (("contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("contacts"."organization_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("contacts"."person_id" = 'b5865666-66bb-47de-b500-b3fff5134fe2' AND "contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR (("contacts"."organization_id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "contacts"."tenant_id" = '095b0a5d-c735-4f09-a906-49dfbe179594') OR (("contacts"."person_id" = 'b5865666-66bb-47de-b500-b3fff5134fe2' AND "contacts"."tenant_id" = '095b0a5d-c735-4f09-a906-49dfbe179594') OR (("parents_contact_relationships"."id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5') OR ("parents_contact_relationships"."id" = '{6E7B2DB8-513F-86D0-D9F2-70E6B254BC93}' AND "contacts"."tenant_id" = '095b0a5d-c735-4f09-a906-49dfbe179594')))))))))))))) AND ("contacts"."id" = "aliased_table"."id")))) AND (organizations.uni_c_active_code NOT IN (3,5,8) OR organizations.uni_c_active_code IS NULL OR organizations.id IS NULL) AND "contacts"."deleted_at" IS NULL AND (contacts.person_id IS NULL OR people.anonymous = false) AND "contacts"."tenant_id" = 'bebb31db-8295-4daf-87ac-09ae875066d5' GROUP BY "contacts"."id" LIMIT 30 OFFSET 0
```

The SQL doesn't throw an error when used with `Contact.find_by_sql(query)`.

### PR DESCRIPTION
**Pull request by lfittl**
Depends on https://github.com/protocolbuffers/protobuf/pull/9218, until
that is merged this can only be used with a custom built protobuf gem.

Fixes #209

### CODE REVIEW

File: lib/pg_query/parse.rb [hunk 1]
```diff
@@ -3,7 +3,13 @@ def self.parse(query)
     result, stderr = parse_protobuf(query)
 
     begin
-      result = PgQuery::ParseResult.decode(result)
+      result = if PgQuery::ParseResult.method(:decode).arity == 1
+                 PgQuery::ParseResult.decode(result)
+               elsif PgQuery::ParseResult.method(:decode).arity == -1
+                 PgQuery::ParseResult.decode(result, max_recursion_depth: 100)
```
Comment (Tassosb) [inline lib/pg_query/parse.rb:9]: Back in v1 the nesting limit was 1000, would you be willing to restore it to 1000 again? That would be comfortably enough for my use case.

Comment (lfittl) [reply lib/pg_query/parse.rb:9]: Good question - I don't see a problem with that, but it'd be good to test if there are any other constraints (e.g. stack size).

Do you have an example query that is deeper than 100 levels? (most that I could find easily were < 100)

Comment (Tassosb) [reply lib/pg_query/parse.rb:9]: Good idea. Here is a query that is deeper than 100 levels. Join conditions get nested within each other in the tree, so a query with enough joins will do the trick. I haven't measured its depth but I think this one is at least 200 levels deep.

```ruby
'SELECT * FROM foo ' + (1..100).to_a.map { |i| "JOIN foo_#{i} ON foo.id = foo_#{i}.foo_id" }.join(' ')
```

Comment (lfittl) [reply lib/pg_query/parse.rb]: The good news is, the fix for this has been merged in Protobuf v3.20.0, so we can now rely on the recursion depth setting when the newer release is active. PR updated, and I'll merge that shortly.

**Comment by Tassosb** [comment]
Thank you @lfittl ! Could we get this out in a new release when you get a chance?
