### PR TITLE
Parse: Detect tables in a SELECT INTO clause as DDL tables

### LINKED ISSUE #280: (Select Into) doesn't return DDL tables
`select info` creates a new table, but the parsed query doesn't return any tables for `ddl_tables`

```
parsed = PgQuery.parse "select * into new_users from users"
parsed.ddl_tables # [] which is wrong, it should contain ["new_users"]
parsed.dml_tables # [] correct
```

Reference: https://www.postgresql.org/docs/current/sql-selectinto.html

### PR DESCRIPTION
**Pull request by lfittl**
Fixes #280

### CODE REVIEW

**Review by keiko713 — APPROVED** [review]
🤳

File: spec/lib/parse_spec.rb [hunk 1]
```diff
@@ -1535,6 +1535,15 @@
     expect(query.call_functions).to eq ['unnest', 'json_build_object', 'row_to_json', 'public.my_function']
   end
 
+  it 'finds the table in a SELECT INTO thats being created' do
```
Comment (olleolleolle) [inline spec/lib/parse_spec.rb:1538]:
```suggestion
  it 'finds the table in a SELECT INTO that is being created' do
```

**Review by olleolleolle — COMMENTED** [review]
Cool feature!

**Review by seanlinsley — APPROVED** [review]
